"""Assemble the single validation report from the section fragments.

The analyses each own a fragment in `report_sections/`: some are hand-written
(the overview, the summary, the three figure notes), and four are regenerated
by their analysis script's `REPORT.write_text(...)`.  This script does not run
those analyses -- it only stitches whatever fragments are committed into
`VALIDATION_REPORT.md`, demoting every fragment heading one level so the
sections nest under a single report title.

Workflow: rerun an analysis (e.g. `analyze_endtoend_residuals.py`) to refresh
its fragment, then rerun this to reassemble the report.

Run from the repository root::

    python validation/build_report.py
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SECTIONS = ROOT / "validation/report_sections"
REPORT = ROOT / "validation/VALIDATION_REPORT.md"

# Explicit order rather than a glob, so the reading path is obvious and the
# figure notes sit next to the analyses they extend.
ORDER = [
    "overview.md",
    "summary.md",
    "endtoend.md",
    "noise_scatter.md",
    "color_term.md",
    "solve_time.md",
    "solve_reachability.md",
    "performance.md",
    "noise_budget.md",
    "extended.md",
]

PREAMBLE = (
    "# CASTOR validation report\n\n"
    "_Generated by `validation/build_report.py` from `validation/report_sections/`;"
    " do not edit this file directly._ Open questions live in"
    " [`QUESTIONS.md`](QUESTIONS.md).\n"
)


def demote(text: str) -> str:
    """Add one level to every ATX heading so `#` -> `##`, `##` -> `###`."""
    return re.sub(r"(?m)^(#{1,5})(?=\s)", r"#\1", text)


def main() -> None:
    parts = [PREAMBLE]
    missing = []
    for name in ORDER:
        path = SECTIONS / name
        if not path.exists():
            missing.append(name)
            continue
        parts.append(demote(path.read_text(encoding="utf-8").strip()))
    if missing:
        raise SystemExit(f"missing fragments: {', '.join(missing)}")

    extras = sorted(p.name for p in SECTIONS.glob("*.md")
                    if p.name not in ORDER)
    if extras:
        raise SystemExit(f"fragments not in ORDER: {', '.join(extras)}")

    REPORT.write_text("\n\n---\n\n".join(parts) + "\n", encoding="utf-8")
    print(f"wrote {REPORT.relative_to(ROOT)} from {len(ORDER)} sections")


if __name__ == "__main__":
    main()
